### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by adrienbrignon** [matteovol/EclataxEngine#3]
Hello guys !
First of all, I wanted to let you know that I love your engine, its so classy.

I was wondering what the state of the project was, as the last commit was 8 months ago.
Do you have any more information on this ?

**dank meme**
![image](https://user-images.githubusercontent.com/10183277/100289519-5fd0cd80-2f79-11eb-9ee1-e5260d66dd4b.png)

**Comment by volpi-m** [comment]
Thanks for all the good things you said about our engine. I cannot be more thrilled to read that you use it for every project you do.

Wow, such meme, much fun.

**Comment by ltabis** [comment]
Ok.

On est pas la pour rigoler.

Je ferme cette issue vue qu'elle n'apporte rien d'utile au projet.

Cordialement.
